
modLoader="javafml" #mandatory
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL="https://github.com/eerussianguy/BlazeMap/issues" #optional
[[mods]] #mandatory
modId="blazemap" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Blaze Map" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/blaze-map" #optional
logoFile="blazemap_logo.png" #optional
credits="Respectable Username for the invaluable help" #optional
authors="LordFokas, EERussianguy (former co-author)" #optional
description='''
The open-source Forge map mod, made by modders for modders.
'''

[[dependencies.blazemap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
